# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-25 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_card_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card',
            new_name='list',
        ),
    ]
